### ISSUE TITLE
Billing history created twice

### ISSUE THREAD

**Issue by pofider** [jsreportonline/main#19]
This [line](https://github.com/jsreportonline/main/blob/master/lib/billing.js#L94) is not "thread" safe and it happened it created two billing history items.

**Comment by pofider** [comment]
We can do something simple I think.

```js
 await reporter.multitenancyRepository.update({
              name: tenant.name,
              creditsBilled: tenant.creditsBilled
            }, update)
```

The idea of the query condition is to avoid duplicate updates. However, the idea `creditsBilled` is the wrong prop, it is not used anyway. I believe it should have been `lastBilledDate`.

However using the date here is probably not so good. Better would be some kind of artifitial counter. Like `tenant.billingCounter`. The update would then look like this:

```js
 await reporter.multitenancyRepository.update({
              name: tenant.name,
              billingCounter: tenant.billingCounter
 }, {
  ...update,
  billingCounter: tenant.billingCounter + 1
})
```

This should guarantee that multiple server won't pass the update query. Because the update is atomic and just one will win.

Additionally I would load just tenant ids to the memory first. And then iterate one by one.

**Comment by bjrmatos** [comment]
i found that using the counter would fail in other case (specifically case 2) 

**case º1**

- 1º server -> adds billing when counter is 8 and it ends increasing it to 9]
- 2º server -> adds billing when counter is 8 because the condition it does not end adding billing history

**case º2**

- 1º server -> adds billing when counter is 8 and it ends increasing it to 9
- 2º server -> adds billing when counter is 9, it ends increasing to 10 and adds duplicated billing history

using a a date like lastBilledDate would also fail in case 2, so i ended saving a timestamp that represents the next billed date, and use that field for the condition in the query.

those changes are ready [here](https://github.com/jsreportonline/main/commit/7979206ee8d79b0372586bba7a80ade9ef9db3a2) and it will be nice to get a review of it to see if there is some concern there.

**Comment by bjrmatos** [comment]
we ended up choosing the counter based solution, because the checkBilling will prevent case 2 to happen and also because the counter is using much less code
