### ISSUE TITLE
Allow using chrome-pool strategy for specific tenant

### ISSUE THREAD

**Issue by pofider** [jsreportonline/main#25]
The database prop tenant.chromePool, or tenant.customWorkerOptions could be set by us.

**Comment by bjrmatos** [comment]
we found that adding options per tenant is more complex than we thought at first, the point to highlight is that in order to apply new options to a running container we need to stop execution of the container and start it again, because we pass options to the container as env vars, which are set with docker command line args. 

we first thought about using the restart command, but that command does not let you change the docker command line args used when the container was created, then we thought that the only way to do this was to delete and create the container again but it seems that there is better option by using the `docker stop` command and then use `docker start ...` command, however we need to test how these command behave.

another option (in case the `docker stop/start` does not work as we think) will be that worker container includes some code to load env vars from some file, then we just need to restart the container and it will pick the new values from that file on boot. from the docker-workers we need to setup sharing a file with the worker container and the docker-workers process, so we can save to a file from docker-workers and read a file from worker container

**Comment by pofider** [comment]
Thinking if we do anyway the most of the init lazily... why we just don't send the configs along with the requests... 

But the chrome-pool is probably not so much important at this moment. However, timeout sounds like a good thing to give higher plans higher timeouts. We should probably implement the general timeout to the request as @bjrmatos suggested and use it in jsreportonline as a primary value.

Something like
free plan: 20s total timeout for request
bronze plan: 50s
silver plan: 80s
gold plan: 120s

**Comment by pofider** [comment]
We have now chrome pool and timeouts don't cause issues now with faster servers.
No plans to invest in this currently.
