### ISSUE TITLE
Last requests logs don't include credits information

### ISSUE THREAD

**Issue by pofider** [jsreportonline/main#29]
![image](https://user-images.githubusercontent.com/2041960/53426962-48e9f980-39e8-11e9-8a89-6f2eca788239.png)

**Comment by bjrmatos** [comment]
the credits logs were not showing because the studio logs saving listener runs before the credits listener (both are afterRender listeners), we need to ensure that the studio logs saving listener runs as the last one, or at least try our best, like for example [runnning the logs saving listener](https://github.com/jsreport/jsreport-studio/blob/master/lib/requestLog.js#L39) inside an initializeListeners
