### ISSUE TITLE
Scheduling fix

### ISSUE THREAD

**Issue by pofider** [jsreportonline/main#32]
Scheduling currently doesn't work for duplicated names.

```
unable to update schedule stateError: The name "Test" already exist in the same folder. existing: "TEST" at module.exports (/usr/src/app/node_modules/jsreport-core/lib/util/createError.js:10:13) at Reporter.createError (/usr/src/app/node_modules/jsreport-core/lib/reporter.js:256:12) at validateDuplicatedName (/usr/src/app/node_mod
```

The problem is that it doesn't reflect multitenancy when updating schedules and the names collision validation throws if there are other entities with the same name.

Solution:

Scheduling should expose a function for updating schedules
```
reportre.scheduling.updateSchedule(q,u,req)
```

jsreportonline main will overwrite it

```
reporter.scheduling.updateSchedule  = async (q,u,req) => {
   const schedule = await  reporter.documentStore.collection('schedules').findOne({_id: q._id})
   req.context.tenantId = schedule.tenantId
   return reporter.documentStore.collection('schedules').update(q,u, req)
}
```

**Comment by pofider** [comment]
The scheduling part of the fix likely needs to be done in a version that is currently used in jsreportonline.

**Comment by bjrmatos** [comment]
we decided to add `beforeProcessJobListeners` listener instead of `updateSchedule `, because it looks a lot more clean to keep the scheduling execution (and all the queries that it does in that process) aware of the request object.

this listener fires with the following arguments `schedule, task, req`, this listener should be used when there is some important information to add to the request context when processing a background tasks. jo uses this listener to add the tenant to the context.

**Comment by bjrmatos** [comment]
for the review, the scheduling update is in [this branch](https://github.com/jsreport/jsreport-scheduling/tree/2.0.4-with-patch-for-jo), if it is ok after review i will merge it to master
