### ISSUE TITLE
413 entity too large for the xlsx template

### ISSUE THREAD

**Issue by pofider** [jsreportonline/main#38]
We have 1M limitation for uploading the xlsx template.
I think the reason was that it is putting some performance risks to the main process.
The 1M is probably too small and we should go with 5.
```
 location /odata/xlsxTemplates {
          client_max_body_size 1M;
```

https://forum.jsreport.net/topic/1297/413-request-entity-too-large

**Comment by pofider** [comment]
Maybe we could run the perf complex part inside the scripts manager. Worth it to check.

**Comment by bjrmatos** [comment]
i've tested the linked case and that 220kb xlsx file turns into 2.4MB json payload when trying to save it in studio, the reason is probably because we duplicate the content of the file in `content` and `contentRaw`, i think that the `content` is the property that consumes more space, considering that it contains the raw data of the xlsx without any compression.

![Captura de pantalla 2019-10-08 a la(s) 6 38 25 p  m](https://user-images.githubusercontent.com/4262050/66441075-f7343380-e9fa-11e9-9169-99bec675f97b.png)

if i change nginx config to 5M then the xlsx template can be saved normally.

**Comment by bjrmatos** [comment]
we have updated the xlsx template upload limit to `5M`(not released yet, but the change is done)
