### ISSUE TITLE
"The communication with your dedicated scriptManager container crashed" only for specific user

### ISSUE THREAD

**Issue by Ackhuman** [jsreportonline/main#51]
We are using JsReport Online to render reports for a survey system that we have developed. Each respondent can generate reports based on their survey responses. It's working for, as far as we can tell, every user but one. For that user, we are getting the following error response:

`Unable to render template.  The communication with your dedicated scriptManager container crashed. This is usually caused by reaching provided resources limits. The container is now about to be restarted. read ECONNRESET`

There are 5 different reports for each respondent and all are failing for this one, so it's not as if it's a particular template, it's just this respondent. The issue is not happening for 3.2.0 on-premises, nor in the Playground. I tried installing the main-1.5.1 package for the JsReport Online version but was not able to resolve all the errors I was getting, so I couldn't get a more detailed error response.

We are using ChromePdf recipe and there is no data binding happening (we do it ahead of time with ASP Razor rendering).

I will attach the header/body/footer templates that are being sent in a password-protected zip. I will email the password to your jsreport.net email address. I can provide more detail if needed.

[surveycenter-error-template.zip](https://github.com/jsreportonline/main/files/8533182/surveycenter-error-template.zip)

**Comment by pofider** [comment]
Thank you, we will take a look what we can do about it.

**Comment by pofider** [comment]
Can you share what extra attributes you send in the request? Some chrome margins? Custom width?
So far the template works for me in the jsreportonline.

The error you get typically means you reached the resource limits. This is often caused by embedding too large images to the pdf because chrome is using the memory extensively during this. Please check this one in particular `image class="logo-cover" src="data:image/jpeg;base64,` it has some 500kb in footer and maybe you could try to use some optimized version of it.

**Comment by Ackhuman** [comment]
I'll try with a more optimized logo and if that doesn't work I will attach the entire serialized request.

**Comment by Ackhuman** [comment]
That was indeed the issue. We didn't think of that because the error message sounded to us like we were reaching the API limits, not that there was a limit on file size. Thank you for the quick response.
